### ISSUE TITLE
line 8, in <module>     import bs4 ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by barkinb** [amalrajan/www.learncpp.com-Crawler#57]
```
Last login: Fri Aug 16 17:21:03 on ttys001
barkinb@mb ~ % cd Downloads/learncpp-download 
barkinb@mb learncpp-download % source bin/activate
(learncpp-download) barkinb@mb learncpp-download % pip install -r requirements.txt
Collecting attrs==23.2.0 (from -r requirements.txt (line 1))
  Downloading attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting Automat==22.10.0 (from -r requirements.txt (line 2))
  Downloading Automat-22.10.0-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 3))
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting certifi==2023.11.17 (from -r requirements.txt (line 4))
  Downloading certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting cffi==1.16.0 (from -r requirements.txt (line 5))
  Downloading cffi-1.16.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (1.5 kB)
Collecting charset-normalizer==3.3.2 (from -r requirements.txt (line 6))
  Downloading charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (33 kB)
Collecting constantly==23.10.4 (from -r requirements.txt (line 7))
  Downloading constantly-23.10.4-py3-none-any.whl.metadata (1.8 kB)
Collecting cryptography==42.0.1 (from -r requirements.txt (line 8))
  Downloading cryptography-42.0.1-cp39-abi3-macosx_10_12_universal2.whl.metadata (5.3 kB)
Collecting cssselect==1.2.0 (from -r requirements.txt (line 9))
  Downloading cssselect-1.2.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting filelock==3.13.1 (from -r requirements.txt (line 10))
  Using cached filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting hyperlink==21.0.0 (from -r requirements.txt (line 11))
  Downloading hyperlink-21.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting idna==3.6 (from -r requirements.txt (line 12))
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting incremental==22.10.0 (from -r requirements.txt (line 13))
  Downloading incremental-22.10.0-py2.py3-none-any.whl.metadata (6.0 kB)
Collecting itemadapter==0.8.0 (from -r requirements.txt (line 14))
  Downloading itemadapter-0.8.0-py3-none-any.whl.metadata (17 kB)
Collecting itemloaders==1.1.0 (from -r requirements.txt (line 15))
  Downloading itemloaders-1.1.0-py3-none-any.whl.metadata (3.9 kB)
Collecting jmespath==1.0.1 (from -r requirements.txt (line 16))
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting lxml==5.1.0 (from -r requirements.txt (line 17))
  Downloading lxml-5.1.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (3.5 kB)
Collecting packaging==23.2 (from -r requirements.txt (line 18))
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting parsel==1.8.1 (from -r requirements.txt (line 19))
  Downloading parsel-1.8.1-py2.py3-none-any.whl.metadata (10 kB)
Collecting pdfkit==1.0.0 (from -r requirements.txt (line 20))
  Downloading pdfkit-1.0.0-py3-none-any.whl.metadata (9.3 kB)
Collecting Protego==0.3.0 (from -r requirements.txt (line 21))
  Downloading Protego-0.3.0-py2.py3-none-any.whl.metadata (5.8 kB)
Collecting pyasn1==0.5.1 (from -r requirements.txt (line 22))
  Downloading pyasn1-0.5.1-py2.py3-none-any.whl.metadata (8.6 kB)
Collecting pyasn1-modules==0.3.0 (from -r requirements.txt (line 23))
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting pycparser==2.21 (from -r requirements.txt (line 24))
  Downloading pycparser-2.21-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting PyDispatcher==2.0.7 (from -r requirements.txt (line 25))
  Downloading PyDispatcher-2.0.7-py3-none-any.whl.metadata (2.4 kB)
Collecting pyOpenSSL==24.0.0 (from -r requirements.txt (line 26))
  Downloading pyOpenSSL-24.0.0-py3-none-any.whl.metadata (12 kB)
Collecting queuelib==1.6.2 (from -r requirements.txt (line 27))
  Downloading queuelib-1.6.2-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting requests==2.31.0 (from -r requirements.txt (line 28))
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting requests-file==1.5.1 (from -r requirements.txt (line 29))
  Downloading requests_file-1.5.1-py2.py3-none-any.whl.metadata (596 bytes)
Collecting Scrapy==2.11.0 (from -r requirements.txt (line 30))
  Downloading Scrapy-2.11.0-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting service-identity==24.1.0 (from -r requirements.txt (line 31))
  Downloading service_identity-24.1.0-py3-none-any.whl.metadata (4.8 kB)
Collecting six==1.16.0 (from -r requirements.txt (line 32))
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting soupsieve==2.5 (from -r requirements.txt (line 33))
  Downloading soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting tldextract==5.1.1 (from -r requirements.txt (line 34))
  Downloading tldextract-5.1.1-py3-none-any.whl.metadata (11 kB)
Collecting Twisted==22.10.0 (from -r requirements.txt (line 35))
  Downloading Twisted-22.10.0-py3-none-any.whl.metadata (15 kB)
Collecting typing_extensions==4.9.0 (from -r requirements.txt (line 36))
  Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting urllib3==2.1.0 (from -r requirements.txt (line 37))
  Downloading urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting w3lib==2.1.2 (from -r requirements.txt (line 38))
  Downloading w3lib-2.1.2-py3-none-any.whl.metadata (1.1 kB)
Collecting zope.interface==6.1 (from -r requirements.txt (line 39))
  Downloading zope.interface-6.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (41 kB)
Collecting setuptools (from Scrapy==2.11.0->-r requirements.txt (line 30))
  Downloading setuptools-72.2.0-py3-none-any.whl.metadata (6.6 kB)
Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
Downloading Automat-22.10.0-py2.py3-none-any.whl (26 kB)
Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
Downloading cffi-1.16.0-cp312-cp312-macosx_11_0_arm64.whl (177 kB)
Downloading charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl (119 kB)
Downloading constantly-23.10.4-py3-none-any.whl (13 kB)
Downloading cryptography-42.0.1-cp39-abi3-macosx_10_12_universal2.whl (5.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 7.9 MB/s eta 0:00:00
Downloading cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Downloading hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Downloading incremental-22.10.0-py2.py3-none-any.whl (16 kB)
Downloading itemadapter-0.8.0-py3-none-any.whl (11 kB)
Downloading itemloaders-1.1.0-py3-none-any.whl (11 kB)
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading lxml-5.1.0-cp312-cp312-macosx_11_0_arm64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 7.9 MB/s eta 0:00:00
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Downloading parsel-1.8.1-py2.py3-none-any.whl (17 kB)
Downloading pdfkit-1.0.0-py3-none-any.whl (12 kB)
Downloading Protego-0.3.0-py2.py3-none-any.whl (8.5 kB)
Downloading pyasn1-0.5.1-py2.py3-none-any.whl (84 kB)
Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
Downloading PyDispatcher-2.0.7-py3-none-any.whl (12 kB)
Downloading pyOpenSSL-24.0.0-py3-none-any.whl (58 kB)
Downloading queuelib-1.6.2-py2.py3-none-any.whl (13 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Downloading Scrapy-2.11.0-py2.py3-none-any.whl (286 kB)
Downloading service_identity-24.1.0-py3-none-any.whl (12 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Downloading tldextract-5.1.1-py3-none-any.whl (97 kB)
Downloading Twisted-22.10.0-py3-none-any.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 3.0 MB/s eta 0:00:00
Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)
Downloading w3lib-2.1.2-py3-none-any.whl (21 kB)
Downloading zope.interface-6.1-cp312-cp312-macosx_11_0_arm64.whl (202 kB)
Downloading setuptools-72.2.0-py3-none-any.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 2.7 MB/s eta 0:00:00
Installing collected packages: PyDispatcher, pdfkit, incremental, w3lib, urllib3, typing_extensions, soupsieve, six, setuptools, queuelib, pycparser, pyasn1, Protego, packaging, lxml, jmespath, itemadapter, idna, filelock, cssselect, constantly, charset-normalizer, certifi, attrs, zope.interface, requests, pyasn1-modules, parsel, hyperlink, cffi, beautifulsoup4, Automat, Twisted, requests-file, itemloaders, cryptography, tldextract, service-identity, pyOpenSSL, Scrapy
Successfully installed Automat-22.10.0 Protego-0.3.0 PyDispatcher-2.0.7 Scrapy-2.11.0 Twisted-22.10.0 attrs-23.2.0 beautifulsoup4-4.12.3 certifi-2023.11.17 cffi-1.16.0 charset-normalizer-3.3.2 constantly-23.10.4 cryptography-42.0.1 cssselect-1.2.0 filelock-3.13.1 hyperlink-21.0.0 idna-3.6 incremental-22.10.0 itemadapter-0.8.0 itemloaders-1.1.0 jmespath-1.0.1 lxml-5.1.0 packaging-23.2 parsel-1.8.1 pdfkit-1.0.0 pyOpenSSL-24.0.0 pyasn1-0.5.1 pyasn1-modules-0.3.0 pycparser-2.21 queuelib-1.6.2 requests-2.31.0 requests-file-1.5.1 service-identity-24.1.0 setuptools-72.2.0 six-1.16.0 soupsieve-2.5 tldextract-5.1.1 typing_extensions-4.9.0 urllib3-2.1.0 w3lib-2.1.2 zope.interface-6.1
(learncpp-download) barkinb@mb learncpp-download % scrapy crawl learncpp 
Traceback (most recent call last):
  File "/opt/homebrew/bin/scrapy", line 8, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/cmdline.py", line 160, in execute
    cmd.crawler_process = CrawlerProcess(settings)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/crawler.py", line 357, in __init__
    super().__init__(settings)
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/crawler.py", line 227, in __init__
    self.spider_loader = self._get_spider_loader(settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/crawler.py", line 221, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/spiderloader.py", line 79, in from_settings
    return cls(settings)
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/spiderloader.py", line 34, in __init__
    self._load_all_spiders()
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/spiderloader.py", line 63, in _load_all_spiders
    for module in walk_modules(name):
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/utils/misc.py", line 106, in walk_modules
    submod = import_module(fullpath)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/barkinb/Downloads/learncpp-download/scraper/spiders/learncpp.py", line 8, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'
(learncpp-download) barkinb@mb learncpp-download % pip install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in ./lib/python3.12/site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in ./lib/python3.12/site-packages (from beautifulsoup4) (2.5)
(learncpp-download) barkinb@mb learncpp-download % scrapy crawl learncpp     
Traceback (most recent call last):
  File "/opt/homebrew/bin/scrapy", line 8, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/cmdline.py", line 160, in execute
    cmd.crawler_process = CrawlerProcess(settings)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/crawler.py", line 357, in __init__
    super().__init__(settings)
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/crawler.py", line 227, in __init__
    self.spider_loader = self._get_spider_loader(settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/crawler.py", line 221, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/spiderloader.py", line 79, in from_settings
    return cls(settings)
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/spiderloader.py", line 34, in __init__
    self._load_all_spiders()
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/spiderloader.py", line 63, in _load_all_spiders
    for module in walk_modules(name):
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/scrapy/2.11.2_3/libexec/lib/python3.12/site-packages/scrapy/utils/misc.py", line 106, in walk_modules
    submod = import_module(fullpath)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/barkinb/Downloads/learncpp-download/scraper/spiders/learncpp.py", line 8, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'
(learncpp-download) barkinb@mb learncpp-download % 
(learncpp-download) barkinb@mb learncpp-download % pip install BeautifulSoup4
Requirement already satisfied: BeautifulSoup4 in ./lib/python3.12/site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in ./lib/python3.12/site-packages (from BeautifulSoup4) (2.5)
(learncpp-download) barkinb@mb learncpp-download % 

```

**Comment by manitejagaddam** [comment]
Install beautifulSoup package the issue will be resolved.

```bash
pip install bs4
```
